/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package VIEW;

import MODEL.PEMASUKAN;
import MODEL.PENGELUARAN;
import MODEL.TRANSAKSI;
import UTIL.TRANSAKSI_MANAGER;
import java.text.NumberFormat;
import java.util.Locale;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.JPopupMenu;
import javax.swing.JMenuItem;
import javax.swing.JTable;


/**
 *
 * @author adellia
 */
// SEBAGAI FORM_CATATAN_KEUANGAN_PRIBADI CLASS ANAK DARI javax.swing.JFrame
public class FORM_CATATAN_KEUANGAN_PRIBADI extends javax.swing.JFrame {
    private TRANSAKSI_MANAGER manager;
    private Object JoptionPane;
    private Object jenis;   
   


    /**
     * Creates new form FORM_CATATAN_KEUANGAN_PRIBADI
     */
    
    // KONSTRUKTOR DARI FORM_CATATAN_KEUANGAN_PRIBADI
    public FORM_CATATAN_KEUANGAN_PRIBADI() {
        initComponents();
        // MEMBUAT IDENTITAS DARI SEBUAH APLIKASI
       this.setTitle ("CATATAN KEUANGAN PRIBADI");
       this.setLocationRelativeTo(this);
       cmbJenis.addItem("PEMASUKAN");
       cmbJenis.addItem("PENGELUARAN");
       cmbJenis.setSelectedIndex(0);   
       
       manager = new TRANSAKSI_MANAGER();
       updateSaldo();
       DefaultTableModel model = (DefaultTableModel) tableTransaksi.getModel();
       lblSaldo.setText("Rp. 0");  
       setupPopup();     
       setupMouseListener();
    }

private void setupPopup() {
    popupMenu = new JPopupMenu();
    deleteItem = new JMenuItem("Hapus Transaksi");
    popupMenu.add(deleteItem);

    deleteItem.addActionListener(e -> hapusTransaksi());
}

private void setupMouseListener() {
    tableTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mousePressed(MouseEvent e) { showPopup(e); }
        @Override
        public void mouseReleased(MouseEvent e) { showPopup(e); }

        private void showPopup(MouseEvent e) {
            if (e.isPopupTrigger()) { // klik kanan
                int row = tableTransaksi.rowAtPoint(e.getPoint());
                if (row >= 0) {
                    tableTransaksi.setRowSelectionInterval(row, row);
                    popupMenu.show(tableTransaksi, e.getX(), e.getY());
                }
            }
        }
    });
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu = new javax.swing.JPopupMenu();
        deleteItem = new javax.swing.JMenuItem();
        panelInput = new javax.swing.JPanel();
        lblJudul = new javax.swing.JLabel();
        txtKeterangan = new javax.swing.JTextField();
        lblKeterangan = new javax.swing.JLabel();
        lblJumlah = new javax.swing.JLabel();
        lblJenis = new javax.swing.JLabel();
        txtJumlah = new javax.swing.JTextField();
        btnTambah = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTransaksi = new javax.swing.JTable();
        lblDaftarTransaksi = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        cmbJenis = new javax.swing.JComboBox<>();

        deleteItem.setText("Hapus Transaksi");
        deleteItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteItemActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelInput.setBackground(new java.awt.Color(255, 204, 204));

        lblJudul.setBackground(new java.awt.Color(255, 204, 204));
        lblJudul.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        lblJudul.setText("APLIKASI CATATAN KEUANGAN PRIBADI");

        txtKeterangan.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        txtKeterangan.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 204)));
        txtKeterangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKeteranganActionPerformed(evt);
            }
        });

        lblKeterangan.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        lblKeterangan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/keterangan.gif"))); // NOI18N
        lblKeterangan.setText("Keterangan         :");

        lblJumlah.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        lblJumlah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/jumlah.gif"))); // NOI18N
        lblJumlah.setText("Jumlah             :");

        lblJenis.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        lblJenis.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/jenis.gif"))); // NOI18N
        lblJenis.setText("Jenis              :");

        txtJumlah.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 204)));
        txtJumlah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahActionPerformed(evt);
            }
        });

        btnTambah.setBackground(new java.awt.Color(255, 255, 204));
        btnTambah.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        btnTambah.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/tambah.gif"))); // NOI18N
        btnTambah.setText("Tambah Transaksi");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        btnHapus.setBackground(new java.awt.Color(255, 255, 204));
        btnHapus.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        btnHapus.setIcon(new javax.swing.ImageIcon(getClass().getResource("/VIEW/hapus.gif"))); // NOI18N
        btnHapus.setText("Hapus Transaksi");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        tableTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "No", "Keterangan", "Jumlah", "Jenis"
            }
        ));
        tableTransaksi.setSelectionBackground(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(tableTransaksi);

        lblDaftarTransaksi.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        lblDaftarTransaksi.setText("DAFTAR TRANSAKSI");

        lblSaldo.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        lblSaldo.setText("Saldo Saat Ini:");

        cmbJenis.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        cmbJenis.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 204)));

        javax.swing.GroupLayout panelInputLayout = new javax.swing.GroupLayout(panelInput);
        panelInput.setLayout(panelInputLayout);
        panelInputLayout.setHorizontalGroup(
            panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelInputLayout.createSequentialGroup()
                        .addComponent(lblSaldo, javax.swing.GroupLayout.PREFERRED_SIZE, 456, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInputLayout.createSequentialGroup()
                        .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelInputLayout.createSequentialGroup()
                                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblKeterangan)
                                    .addComponent(lblJumlah)
                                    .addComponent(lblJenis))
                                .addGap(18, 18, 18)
                                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtKeterangan)
                                    .addComponent(txtJumlah)
                                    .addComponent(cmbJenis, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelInputLayout.createSequentialGroup()
                                .addComponent(btnTambah)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnHapus)))
                        .addGap(94, 94, 94))))
            .addGroup(panelInputLayout.createSequentialGroup()
                .addGap(222, 222, 222)
                .addComponent(lblDaftarTransaksi)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelInputLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblJudul)
                .addGap(130, 130, 130))
        );
        panelInputLayout.setVerticalGroup(
            panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelInputLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(lblJudul)
                .addGap(26, 26, 26)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKeterangan, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKeterangan))
                .addGap(28, 28, 28)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJumlah)
                    .addComponent(txtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblJenis)
                    .addComponent(cmbJenis, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(panelInputLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHapus)
                    .addComponent(btnTambah))
                .addGap(34, 34, 34)
                .addComponent(lblDaftarTransaksi)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblSaldo)
                .addContainerGap(43, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelInput, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        // TODO add your handling code here:
        int id = manager.generateId(); 
        String keterangan = txtKeterangan.getText();
        double jumlah = Double.parseDouble(txtJumlah.getText());
        
        Object selected = cmbJenis.getSelectedItem();
        TRANSAKSI t = null;  
        if (selected != null) {
            String jenis = selected.toString();
            if ("PEMASUKAN".equals(jenis)) {
                t = new PEMASUKAN(id, keterangan, jumlah);
            } else {
                t = new PENGELUARAN(id, keterangan, jumlah);
            }
        } else {
            JOptionPane.showMessageDialog(this, "Pilih jenis transaksi terlebih dahulu!");
        }
        
        manager.tambah(t);
        JOptionPane.showMessageDialog(this, "Transaksi berhasil di tambahkan.");
        tampilkanOutput();
        updateSaldo();    
    }//GEN-LAST:event_btnTambahActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        int row = tableTransaksi.getSelectedRow();
        if (row == -1){
            
            JOptionPane.showMessageDialog(this, "Pilih transaksi yang akan dihapus.");
            return;
        }
        
        // AMBIL ID DARI KOLOM PERTAMA
        int id = Integer.parseInt(tableTransaksi.getValueAt(row,0).toString()
        );
        
        manager.hapus(id);
        tampilkanOutput();
        updateSaldo();
    }//GEN-LAST:event_btnHapusActionPerformed

    private void deleteItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteItemActionPerformed
        // TODO add your handling code here:
    int selectedRow = tableTransaksi.getSelectedRow();
if (selectedRow != -1) {
    String jenis = tableTransaksi.getValueAt(selectedRow, 1).toString();
    String nominalStr = tableTransaksi.getValueAt(selectedRow, 2).toString();
    int nominal = Integer.parseInt(nominalStr.replaceAll("[^0-9]", ""));

    int confirm = JOptionPane.showConfirmDialog(this,
            "Apakah yakin ingin menghapus transaksi ini?",
            "Konfirmasi Hapus",
            JOptionPane.YES_NO_OPTION);

    if (confirm == JOptionPane.YES_OPTION) {
       
        DefaultTableModel model = (DefaultTableModel) tableTransaksi.getModel();
        model.removeRow(selectedRow);
        
        if (jenis.equalsIgnoreCase("Pemasukan")) {
            manager.setSaldo(manager.getSaldo() - nominal);
        } else {
            manager.setSaldo(manager.getSaldo() + nominal);
        }

        NumberFormat rupiah = NumberFormat.getCurrencyInstance(new Locale("id", "ID"));
        lblSaldo.setText("Saldo Saat Ini: " + rupiah.format(manager.getSaldo()));

        JOptionPane.showMessageDialog(this,
                "Transaksi berhasil dihapus!\nSaldo saat ini: " + rupiah.format(manager.getSaldo()));
    }
}

    }//GEN-LAST:event_deleteItemActionPerformed

    private void txtJumlahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahActionPerformed

    private void txtKeteranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKeteranganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKeteranganActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FORM_CATATAN_KEUANGAN_PRIBADI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FORM_CATATAN_KEUANGAN_PRIBADI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FORM_CATATAN_KEUANGAN_PRIBADI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FORM_CATATAN_KEUANGAN_PRIBADI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FORM_CATATAN_KEUANGAN_PRIBADI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cmbJenis;
    private javax.swing.JMenuItem deleteItem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDaftarTransaksi;
    private javax.swing.JLabel lblJenis;
    private javax.swing.JLabel lblJudul;
    private javax.swing.JLabel lblJumlah;
    private javax.swing.JLabel lblKeterangan;
    private javax.swing.JLabel lblSaldo;
    private javax.swing.JPanel panelInput;
    private javax.swing.JPopupMenu popupMenu;
    private javax.swing.JTable tableTransaksi;
    private javax.swing.JTextField txtJumlah;
    private javax.swing.JTextField txtKeterangan;
    // End of variables declaration//GEN-END:variables

    private void tampilkanOutput() {

    DefaultTableModel model = (DefaultTableModel) tableTransaksi.getModel();
    model.setRowCount(0);

    for (TRANSAKSI t : manager.getSemua()) {
        model.addRow(new Object[]{
            t.getId(),
            t.getKeterangan(),
            t.getJumlah(),
            t.getJenis()
        });
         }
      }

    private void updateSaldo() {
        NumberFormat rupiah =
            NumberFormat.getCurrencyInstance(new Locale("id", "ID"));

        lblSaldo.setText("Saldo Saat Ini: " +
            rupiah.format(manager.getSaldo()));
    }

    private void hapusTransaksi() {
    int selectedRow = tableTransaksi.getSelectedRow();
    if (selectedRow != -1) {
        DefaultTableModel model = (DefaultTableModel) tableTransaksi.getModel();
        String jenis = tableTransaksi.getValueAt(selectedRow, 1).toString();
        String nominalStr = tableTransaksi.getValueAt(selectedRow, 2).toString();
        int nominal = Integer.parseInt(nominalStr.replaceAll("[^0-9]", ""));

        int confirm = JOptionPane.showConfirmDialog(this,
                "Apakah kamu yakin ingin menghapus transaksi ini? ^^",
                "Konfirmasi Hapus",
                JOptionPane.YES_NO_OPTION);
        
        if (confirm == JOptionPane.YES_OPTION) {
            model.removeRow(selectedRow);
            if (jenis.equalsIgnoreCase("Pemasukan")) {
                manager.setSaldo(manager.getSaldo() - nominal);
            } else if (jenis.equalsIgnoreCase("Pengeluaran")) {
                manager.setSaldo(manager.getSaldo() + nominal);
            }
            
            NumberFormat rupiah = NumberFormat.getCurrencyInstance(new Locale("id", "ID"));
            lblSaldo.setText("Saldo Saat Ini: " + rupiah.format(manager.getSaldo()));

            JOptionPane.showMessageDialog(this,
                    "Yey! Transaksi berhasil dihapus!");
        }
    }
}
}
