/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package UAS_PEMROGRAMAN_2;

import java.sql.DriverManager;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.sql.PreparedStatement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;


/**
 *
 * @author adellia
 */

// SEBAGAI FORM_GUI CLASS ANAK DARI javax.swing.JFrame
public class FORM_GUI extends javax.swing.JFrame {
    private Object cbPembayaran;
    private Object statusKoneksi;
    private String sql;
    private String nama_produk;
    private int harga;
    private String idproduk;
    

    /**
     * Creates new form FORM_GUI
     */
    
    // MEMBUAT OBJEK DARI CLASS KONEKSI
    KONEKSI konek = new KONEKSI();
    
    // KONSTRUKTOR DARI FORM GUI
    public FORM_GUI() {
        initComponents();
        // MEMBUAT IDENTITAS
        this.setTitle("MABEL STORE");
        setLocationRelativeTo(this);
        
        // MEMANGGIL METHOD DARI CLASS KONEKSI
        konek.koneksi();
        
        // MENAMPIILKAN TABEL LIST PRODUK
        selectlistproduk();
        // MENAMPILKAN TABEL RIWYAT TRANSAKSI
        selectriwayat();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabPane = new javax.swing.JTabbedPane();
        panelMenu = new javax.swing.JPanel();
        labelBanner1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        scrollPane_listproduk = new javax.swing.JScrollPane();
        tabelListProduk = new javax.swing.JTable();
        labelTopUp1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelIdProduk = new javax.swing.JLabel();
        labelNamaProduk = new javax.swing.JLabel();
        labelIdProduk2 = new javax.swing.JLabel();
        idProduk = new javax.swing.JTextField();
        namaProduk = new javax.swing.JTextField();
        hargaProduk = new javax.swing.JTextField();
        buttonUpdate = new javax.swing.JButton();
        buttonTambah = new javax.swing.JButton();
        buttonDelete = new javax.swing.JButton();
        button_reset = new javax.swing.JButton();
        panelPembelian = new javax.swing.JPanel();
        panelDataAkun = new javax.swing.JPanel();
        labelDataAkun = new javax.swing.JLabel();
        labelIdUser = new javax.swing.JLabel();
        labelServer = new javax.swing.JLabel();
        idUser = new javax.swing.JTextField();
        idServer = new javax.swing.JTextField();
        panelPilihPembayaran = new javax.swing.JPanel();
        labelPilihPembayaran = new javax.swing.JLabel();
        labelPembayaran = new javax.swing.JLabel();
        cbPilihPembayaran = new javax.swing.JComboBox<>();
        jPanel3 = new javax.swing.JPanel();
        detailKontak = new javax.swing.JLabel();
        labelEmail = new javax.swing.JLabel();
        labelNoHP = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        noHP = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        areaStrukPembelian = new javax.swing.JTextArea();
        buttonBeliSekarang = new javax.swing.JButton();
        panelRiwayat = new javax.swing.JPanel();
        scrollPane_riwayat = new javax.swing.JScrollPane();
        tabelRiwayat = new javax.swing.JTable();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idProduk2 = new javax.swing.JTextField();
        hargaProduk2 = new javax.swing.JTextField();
        button_reset2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelMenu.setBackground(new java.awt.Color(0, 0, 0));

        labelBanner1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/IMAGE/Banner.jpg"))); // NOI18N
        labelBanner1.setText("jLabel1");

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "List Produk", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("OCR A Extended", 1, 14))); // NOI18N

        tabelListProduk.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID PRODUK", "NAMA PRODUK", "HARGA"
            }
        ));
        tabelListProduk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelListProdukMouseClicked(evt);
            }
        });
        scrollPane_listproduk.setViewportView(tabelListProduk);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPane_listproduk, javax.swing.GroupLayout.DEFAULT_SIZE, 671, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrollPane_listproduk, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
        );

        labelTopUp1.setFont(new java.awt.Font("OCR A Extended", 1, 18)); // NOI18N
        labelTopUp1.setForeground(new java.awt.Color(255, 255, 255));
        labelTopUp1.setText("=== TOP UP DIAMOND MOBILE LEGENDS ===");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Pemesanan Produk", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("OCR A Extended", 1, 14))); // NOI18N

        labelIdProduk.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        labelIdProduk.setText("ID PRODUK");

        labelNamaProduk.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        labelNamaProduk.setText("NAMA PRODUK");

        labelIdProduk2.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        labelIdProduk2.setText("HARGA");

        namaProduk.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelIdProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelNamaProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelIdProduk2, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(98, 98, 98)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(idProduk)
                    .addComponent(namaProduk)
                    .addComponent(hargaProduk, javax.swing.GroupLayout.DEFAULT_SIZE, 289, Short.MAX_VALUE))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(2, 2, 2)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIdProduk)
                    .addComponent(idProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNamaProduk)
                    .addComponent(namaProduk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelIdProduk2)
                    .addComponent(hargaProduk, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        buttonUpdate.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        buttonUpdate.setText("Update Produk");
        buttonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUpdateActionPerformed(evt);
            }
        });

        buttonTambah.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        buttonTambah.setText("Tambah Transaksi");
        buttonTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonTambahActionPerformed(evt);
            }
        });

        buttonDelete.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        buttonDelete.setText("Hapus Produk");
        buttonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDeleteActionPerformed(evt);
            }
        });

        button_reset.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        button_reset.setText("RESET");
        button_reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_resetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelMenuLayout = new javax.swing.GroupLayout(panelMenu);
        panelMenu.setLayout(panelMenuLayout);
        panelMenuLayout.setHorizontalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                .addContainerGap(305, Short.MAX_VALUE)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelMenuLayout.createSequentialGroup()
                        .addComponent(button_reset)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(buttonUpdate)
                        .addGap(12, 12, 12))
                    .addComponent(buttonTambah, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(62, 62, 62))
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(158, 158, 158)
                        .addComponent(labelTopUp1))
                    .addGroup(panelMenuLayout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelBanner1, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelMenuLayout.setVerticalGroup(
            panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelBanner1, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelTopUp1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDelete)
                    .addComponent(button_reset)
                    .addComponent(buttonUpdate))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(buttonTambah)
                .addContainerGap(68, Short.MAX_VALUE))
        );

        tabPane.addTab("Menu", panelMenu);

        panelPembelian.setBackground(new java.awt.Color(255, 204, 204));

        labelDataAkun.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        labelDataAkun.setText("Masukkan Data Akun");

        labelIdUser.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        labelIdUser.setText("ID USER");

        labelServer.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        labelServer.setText("SERVER");

        javax.swing.GroupLayout panelDataAkunLayout = new javax.swing.GroupLayout(panelDataAkun);
        panelDataAkun.setLayout(panelDataAkunLayout);
        panelDataAkunLayout.setHorizontalGroup(
            panelDataAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataAkunLayout.createSequentialGroup()
                .addGroup(panelDataAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelDataAkunLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(panelDataAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelIdUser)
                            .addComponent(labelServer))
                        .addGap(45, 45, 45)
                        .addGroup(panelDataAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(idServer, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                            .addComponent(idUser)))
                    .addGroup(panelDataAkunLayout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(labelDataAkun)))
                .addContainerGap(56, Short.MAX_VALUE))
        );
        panelDataAkunLayout.setVerticalGroup(
            panelDataAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDataAkunLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelDataAkun, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDataAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelIdUser)
                    .addComponent(idUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelDataAkunLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelServer)
                    .addComponent(idServer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        labelPilihPembayaran.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        labelPilihPembayaran.setText("Pilih Pembayaran");

        labelPembayaran.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        labelPembayaran.setText("Pembayaran");

        cbPilihPembayaran.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DANA", "GOPAY", "OVO", "QRIS", " " }));

        javax.swing.GroupLayout panelPilihPembayaranLayout = new javax.swing.GroupLayout(panelPilihPembayaran);
        panelPilihPembayaran.setLayout(panelPilihPembayaranLayout);
        panelPilihPembayaranLayout.setHorizontalGroup(
            panelPilihPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPilihPembayaranLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(labelPembayaran)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addComponent(cbPilihPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23))
            .addGroup(panelPilihPembayaranLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(labelPilihPembayaran)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelPilihPembayaranLayout.setVerticalGroup(
            panelPilihPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPilihPembayaranLayout.createSequentialGroup()
                .addComponent(labelPilihPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(panelPilihPembayaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPembayaran)
                    .addComponent(cbPilihPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        detailKontak.setFont(new java.awt.Font("OCR A Extended", 1, 14)); // NOI18N
        detailKontak.setText("Detail Kontak");

        labelEmail.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        labelEmail.setText("Email");

        labelNoHP.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        labelNoHP.setText("No. HP");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelEmail)
                    .addComponent(labelNoHP))
                .addGap(56, 56, 56)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(email, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE)
                    .addComponent(noHP))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(detailKontak)
                .addGap(89, 89, 89))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(detailKontak, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelEmail)
                    .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNoHP)
                    .addComponent(noHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(31, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "DETAIL TRANSAKSI", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("OCR A Extended", 1, 12)))), "Struk Pembelian ^^", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("OCR A Extended", 1, 14))); // NOI18N

        areaStrukPembelian.setColumns(20);
        areaStrukPembelian.setRows(5);
        areaStrukPembelian.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                areaStrukPembelianMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(areaStrukPembelian);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 237, Short.MAX_VALUE)
        );

        buttonBeliSekarang.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        buttonBeliSekarang.setText("Beli Sekarang");
        buttonBeliSekarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBeliSekarangActionPerformed(evt);
            }
        });

        panelRiwayat.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Riwayat Transaksi", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("OCR A Extended", 1, 14))); // NOI18N
        panelRiwayat.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        panelRiwayat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelRiwayatMouseClicked(evt);
            }
        });

        tabelRiwayat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "ID INVOICE", "ID USER", "SERVER", "EMAIL", "NO. HP", "ID PRODUK", "HARGA", "TANGGAL"
            }
        ));
        tabelRiwayat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelRiwayatMouseClicked(evt);
            }
        });
        scrollPane_riwayat.setViewportView(tabelRiwayat);

        javax.swing.GroupLayout panelRiwayatLayout = new javax.swing.GroupLayout(panelRiwayat);
        panelRiwayat.setLayout(panelRiwayatLayout);
        panelRiwayatLayout.setHorizontalGroup(
            panelRiwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRiwayatLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPane_riwayat, javax.swing.GroupLayout.PREFERRED_SIZE, 685, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(335, Short.MAX_VALUE))
        );
        panelRiwayatLayout.setVerticalGroup(
            panelRiwayatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRiwayatLayout.createSequentialGroup()
                .addComponent(scrollPane_riwayat, javax.swing.GroupLayout.DEFAULT_SIZE, 214, Short.MAX_VALUE)
                .addContainerGap())
        );

        jLabel1.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        jLabel1.setText("ID PRODUK");

        jLabel2.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        jLabel2.setText("HARGA");

        hargaProduk2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaProduk2ActionPerformed(evt);
            }
        });

        button_reset2.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        button_reset2.setText("RESET");
        button_reset2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_reset2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelPembelianLayout = new javax.swing.GroupLayout(panelPembelian);
        panelPembelian.setLayout(panelPembelianLayout);
        panelPembelianLayout.setHorizontalGroup(
            panelPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPembelianLayout.createSequentialGroup()
                .addGroup(panelPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPembelianLayout.createSequentialGroup()
                        .addGroup(panelPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panelPembelianLayout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(panelPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(panelPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(panelDataAkun, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(panelPilihPembayaran, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(panelPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panelPembelianLayout.createSequentialGroup()
                                        .addGap(49, 49, 49)
                                        .addGroup(panelPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(panelPembelianLayout.createSequentialGroup()
                                                .addComponent(buttonBeliSekarang)
                                                .addGap(110, 110, 110)
                                                .addComponent(button_reset2))
                                            .addGroup(panelPembelianLayout.createSequentialGroup()
                                                .addGroup(panelPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                    .addComponent(jLabel1)
                                                    .addComponent(jLabel2))
                                                .addGap(90, 90, 90)
                                                .addGroup(panelPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addComponent(idProduk2, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                                    .addComponent(hargaProduk2)))))
                                    .addGroup(panelPembelianLayout.createSequentialGroup()
                                        .addGap(28, 28, 28)
                                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(panelPembelianLayout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(panelRiwayat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jSeparator2))
                .addContainerGap())
        );
        panelPembelianLayout.setVerticalGroup(
            panelPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPembelianLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(panelPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(panelPembelianLayout.createSequentialGroup()
                        .addGroup(panelPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(idProduk2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(panelPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(hargaProduk2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(panelPembelianLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(buttonBeliSekarang)
                            .addComponent(button_reset2)))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, panelPembelianLayout.createSequentialGroup()
                        .addComponent(panelDataAkun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelPilihPembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRiwayat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tabPane.addTab("Data", panelPembelian);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tabPane, javax.swing.GroupLayout.PREFERRED_SIZE, 718, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(tabPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    // MENDEKLARASIKAN VARIABEL STATEMEN UNTUK MENGIRIM QUERY SQL
    Statement pst;
    // MENDEKLARASIKAN RESULTSET UNTUK MENAMPUNG HASIL DATA DARI DATABASE
    java.sql.ResultSet rs;
    
     public void selectlistproduk(){
        konek.koneksi();
        try {
            
            String sql = "select*from listproduk";
            
            // MEMBUAT PREPARED STATEMENT MENGGUNAKAN KONEKSI YANG SEDANG AKTIF
            pst = konek.con.prepareStatement(sql);
            // MENJALANKAN QUERY DAN MENYIMPAN HASILNYA KE DALAM VARIABEL rs (RESULTSET)
            rs = pst.executeQuery(sql);
            
            /* MENGUBAH HASIL DARI DATABASE (rs) MENJADI FORMAT TABEL SECARA OTOMATIS
           DAN MENAMPILKANNYA PADA KOMPONEN tabelListProduk DI LAYAR */
            tabelListProduk.setModel(DbUtils.resultSetToTableModel(rs));
            
        } catch (Exception e){
            
            JOptionPane.showMessageDialog(null, e);
            
        }
        
    }
     
 private void selectriwayat() {
    DefaultTableModel model = new DefaultTableModel();
    model.addColumn("INVOICE");
    model.addColumn("ID USER");
    model.addColumn("SERVER");
    model.addColumn("EMAIL");
    model.addColumn("NO HP");
    model.addColumn("ID PRODUK");
    model.addColumn("HARGA");
    model.addColumn("TANGGAL");

    try {
        Connection con = konek.koneksi();
        
        // MEMBUAT OBJEK STATEMENT UNTUK MENGIRIM PERINTAH SQL
        Statement st = con.createStatement();
        // MENJALANKAN QUERY UNTUK MENGAMBIL SEMUA DATA DARI TABEL
        ResultSet rs = st.executeQuery("SELECT * FROM tabelriwayat");
        
        // MELAKUKAN LOOPING SELAMA DATA DI DALAM RESULTSET MASIH ADA
        while (rs.next()) {
            model.addRow(new Object[]{
                
                // rs.getString atau rs.getInt: CARA MENGAMBIL NILAI SESUAI TIPE DATA
                rs.getString("invoice"),  
                rs.getInt("id_user"),
                rs.getInt("server"),
                rs.getString("email"),
                rs.getString("no_hp"),
                rs.getInt("id_produk"),
                rs.getInt("harga"),
                rs.getTimestamp("tanggal")
            });
        }

        tabelRiwayat.setModel(model); 

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
}

    private void buttonBeliSekarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBeliSekarangActionPerformed
        // TODO add your handling code here:                                               
        // MENGAMBIL INPUT TEKS DARI FORM GUI DAN DISIMPAN KE DALAM VARIABEL STRING
        String id_u = idUser.getText(); 
        String serv = idServer.getText();
        String mail = email.getText();
        String hp = noHP.getText();
        String idproduk = idProduk.getText();
    
if (hargaProduk.getText().isEmpty() || idUser.getText().isEmpty()) { 
    JOptionPane.showMessageDialog(null, "lengkapi data akun dan pilih produk ya ~");
    return;
}

    try {
        
        // MENGUBAH INPUT HARGA DARI STRING (TEKS) MENJADI INT (ANGKA)
        int harga = Integer.parseInt(hargaProduk.getText());   
        
        Connection con = konek.koneksi();
        
        String sql = "INSERT INTO tabelRiwayat (id_user, server, email, no_hp, id_produk, harga) VALUES (?, ?, ?, ?, ?, ?)";
        PreparedStatement pst = con.prepareStatement(sql);

        pst.setString(1, id_u);
        pst.setString(2, serv);
        pst.setString(3, mail);
        pst.setString(4, hp);
        pst.setString(5, idproduk);
        pst.setInt(6, harga); 

        pst.executeUpdate();
        
        selectriwayat();
        
        // MENGAMBIL WAKTU SISTEM SAAT INI UNTUK DI CATAT PADA STRUK
        java.util.Date d = new java.util.Date();
        // SimpleDataFormat: MERAPIKAN TAMPILAN WAKTU AGAR MANUSIA BISA MEMBACANYA DENGAN MUDAH DIBANDING FORMAT ASLI KOMPUTER
        java.text.SimpleDateFormat sdf = new java.text.SimpleDateFormat("dd/MM/yyyy HH:mm");
        String tgl = sdf.format(d);
        
        areaStrukPembelian.setText(
    "================================\n" +
    "       STRUK PEMBAYARAN        \n" +
    "================================\n" +
    " TANGGAL  : " + tgl + "\n" +
    "================================\n" +
    " ID USER  : " + idUser.getText() + "\n" +
    " SERVER   : " + idServer.getText() + "\n" +
    " EMAIL    : " + email.getText() + "\n" +
    " NO. HP   : " + noHP.getText() + "\n" +
    "================================\n" +
    " ITEM     : " + namaProduk.getText() + "\n" +
    " TOTAL    : Rp " + hargaProduk.getText() + "\n" +
    " PEMBAYARAN     : " + cbPilihPembayaran.getSelectedItem() + "\n" +
    "================================\n" +
    "        TRANSAKSI BERHASIL      \n" +
    "================================\n" + "");

        JOptionPane.showMessageDialog(null, "pembelian sudah di proses !");

    } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error: " + e.getMessage());
    }

    }//GEN-LAST:event_buttonBeliSekarangActionPerformed

    private void buttonTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonTambahActionPerformed
        // TODO add your handling code here:
       
    if (idProduk.getText().isEmpty() || hargaProduk.getText().isEmpty()) {
        JOptionPane.showMessageDialog(null, "pilih dulu produknya di tabel biar bisa geser !!!");
        return; 
    }

    try {
        String id = idProduk.getText(); 
        int harga = Integer.parseInt(hargaProduk.getText()); 
        
        // MEMINDAHKAN DATA KE FORM BERIKUTNYA
        idProduk2.setText(id); 
        hargaProduk2.setText(String.valueOf(harga)); 
        
        // PINDAH KE HALAMAN TAB SELANJUTNYA SECARA OTOMATIS
        tabPane.setSelectedIndex(1); 

    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(null, "harga harus angka okey...");
    }

        
    }//GEN-LAST:event_buttonTambahActionPerformed

    private void buttonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUpdateActionPerformed
        // TODO add your handling code here:
       
       try {
           String id = idProduk.getText(); 
           String nama = namaProduk.getText();
           String harga = hargaProduk.getText();
   
           String sql = "UPDATE listproduk SET nama_produk = ?, harga = ? WHERE id_produk = ?";
           
           java.sql.PreparedStatement pst = konek.con.prepareStatement(sql);
           pst.setString(1, nama);
           pst.setString(2, harga);
           pst.setString(3, id);
           
           int status = pst.executeUpdate();
           
           if (status > 0) {
               JOptionPane.showMessageDialog(null, "produk berhasil diperbarui !");
               selectlistproduk(); 
           } else {
        JOptionPane.showMessageDialog(null, "gagal: ID tidak ditemukan !");
    }
    
} catch (Exception e) {
    JOptionPane.showMessageDialog(null, "Error Update: " + e.getMessage());
}
        
    }//GEN-LAST:event_buttonUpdateActionPerformed

    private void tabelListProdukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelListProdukMouseClicked
        // TODO add your handling code here:
        
        int row = tabelListProduk.getSelectedRow();
        if (row == -1){
            return;
        }
        
        String id_produk = tabelListProduk.getValueAt(row, 0).toString();
        String nama_produk = tabelListProduk.getValueAt(row, 1).toString();
        String harga = tabelListProduk.getValueAt(row, 2).toString();
        
        idProduk.setText(id_produk);
        namaProduk.setText(nama_produk);
        hargaProduk.setText(harga);
        
    }//GEN-LAST:event_tabelListProdukMouseClicked

    private void button_resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_resetActionPerformed
        // TODO add your handling code here:
        namaProduk.setText("");
        hargaProduk.setText("");
        
    }//GEN-LAST:event_button_resetActionPerformed

    private void buttonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDeleteActionPerformed
        // TODO add your handling code here:
                                          
   try {

        konek.koneksi(); 
       
        String id = idProduk.getText(); 
        String sql = "DELETE FROM listproduk WHERE id_produk = ?";
        
        java.sql.PreparedStatement pst = konek.con.prepareStatement(sql);
        pst.setString(1, id);
     
        int status = pst.executeUpdate();
        if (status > 0) {
            JOptionPane.showMessageDialog(null, "produk berhasil dihapus !");
            
           selectlistproduk();
           
        } else {
            JOptionPane.showMessageDialog(null, "produk tidak ditemukan di database !");
        }
        
    } catch (Exception e) {
      
        JOptionPane.showMessageDialog(null, "Error SQL: " + e.getMessage());
    }

    }//GEN-LAST:event_buttonDeleteActionPerformed

    private void hargaProduk2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaProduk2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaProduk2ActionPerformed

    private void button_reset2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_reset2ActionPerformed
        // TODO add your handling code here:
      areaStrukPembelian.setText("");
        
    }//GEN-LAST:event_button_reset2ActionPerformed

    private void panelRiwayatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelRiwayatMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_panelRiwayatMouseClicked

    private void tabelRiwayatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelRiwayatMouseClicked
        // TODO add your handling code here:
        int row = tabelRiwayat.getSelectedRow();

    // MENGAMBIL DATA DARI SETIAP KOLOM PADA BARIS YANG DIPILIH
    // INDEKS (0, 1, 2, DST) HARUS SESUAI DENGAN URUTAN KOLOM DI TABEL
    String invoice = tabelRiwayat.getValueAt(row, 0).toString();
    String id_u    = tabelRiwayat.getValueAt(row, 1).toString();
    String serv    = tabelRiwayat.getValueAt(row, 2).toString();
    String mail    = tabelRiwayat.getValueAt(row, 3).toString();
    String hp      = tabelRiwayat.getValueAt(row, 4).toString();
    String id_p    = tabelRiwayat.getValueAt(row, 5).toString();
    String harga   = tabelRiwayat.getValueAt(row, 6).toString();
    String tgl     = tabelRiwayat.getValueAt(row, 7).toString();

 
    areaStrukPembelian.setText(
        "====================================\n" +
        "           STRUK PEMBELIAN         \n" +
        "====================================\n" +
        " INVOICE    : " + invoice + "\n" +
        " TANGGAL    : " + tgl + "\n" +
        "------------------------------------\n" +
        " ID USER    : " + id_u + " (" + serv + ")\n" +
        " EMAIL      : " + mail + "\n" +
        " NO. HP     : " + hp + "\n" +
        "====================================\n" +
        " ID PRODUK  : " + id_p + "\n" +
        " TOTAL      : Rp " + harga + "\n" +
        "====================================\n" +
        "         RIWAYAT TRANSAKSI          \n" +
        "====================================\n"
    );

        
    }//GEN-LAST:event_tabelRiwayatMouseClicked

    private void areaStrukPembelianMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_areaStrukPembelianMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_areaStrukPembelianMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Windows look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FORM_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FORM_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FORM_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FORM_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
try {
    for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
        if ("Windows".equals(info.getName())) {
            javax.swing.UIManager.setLookAndFeel(info.getClassName());
            break;
        }
    }
} catch (Exception e) {
    e.printStackTrace();
}

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FORM_GUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaStrukPembelian;
    private javax.swing.JButton buttonBeliSekarang;
    private javax.swing.JButton buttonDelete;
    private javax.swing.JButton buttonTambah;
    private javax.swing.JButton buttonUpdate;
    private javax.swing.JButton button_reset;
    private javax.swing.JButton button_reset2;
    private javax.swing.JComboBox<String> cbPilihPembayaran;
    private javax.swing.JLabel detailKontak;
    private javax.swing.JTextField email;
    private javax.swing.JTextField hargaProduk;
    private javax.swing.JTextField hargaProduk2;
    private javax.swing.JTextField idProduk;
    private javax.swing.JTextField idProduk2;
    private javax.swing.JTextField idServer;
    private javax.swing.JTextField idUser;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelBanner1;
    private javax.swing.JLabel labelDataAkun;
    private javax.swing.JLabel labelEmail;
    private javax.swing.JLabel labelIdProduk;
    private javax.swing.JLabel labelIdProduk2;
    private javax.swing.JLabel labelIdUser;
    private javax.swing.JLabel labelNamaProduk;
    private javax.swing.JLabel labelNoHP;
    private javax.swing.JLabel labelPembayaran;
    private javax.swing.JLabel labelPilihPembayaran;
    private javax.swing.JLabel labelServer;
    private javax.swing.JLabel labelTopUp1;
    private javax.swing.JTextField namaProduk;
    private javax.swing.JTextField noHP;
    private javax.swing.JPanel panelDataAkun;
    private javax.swing.JPanel panelMenu;
    private javax.swing.JPanel panelPembelian;
    private javax.swing.JPanel panelPilihPembayaran;
    private javax.swing.JPanel panelRiwayat;
    private javax.swing.JScrollPane scrollPane_listproduk;
    private javax.swing.JScrollPane scrollPane_riwayat;
    private javax.swing.JTabbedPane tabPane;
    private javax.swing.JTable tabelListProduk;
    private javax.swing.JTable tabelRiwayat;
    // End of variables declaration//GEN-END:variables
}
